/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemadeventas;

import javax.swing.JOptionPane;

/**
 *
 * @author demet
 */
public class guiapp extends javax.swing.JFrame {

    /**
     * Creates new form guiapp
     */
    public guiapp() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Log In");
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        loginfoto = new javax.swing.JLabel();
        pswdfield = new javax.swing.JPasswordField();
        loginbutton = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        userfield = new javax.swing.JTextField();
        pswd = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuopciones = new javax.swing.JMenu();
        creadopor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(0, 255, 204));

        loginfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rsz_penguin.png"))); // NOI18N

        pswdfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdfieldActionPerformed(evt);
            }
        });

        loginbutton.setBackground(new java.awt.Color(0, 51, 255));
        loginbutton.setText("Ingrese al Sistema");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        user.setText("Usuario");

        pswd.setText("Contrasena");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(loginfoto)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(loginbutton)
                        .addGap(149, 149, 149))))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pswdfield, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(userfield)
                    .addComponent(pswd)
                    .addComponent(user))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(loginfoto)
                .addGap(41, 41, 41)
                .addComponent(user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userfield)
                .addGap(18, 18, 18)
                .addComponent(pswd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pswdfield, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(loginbutton)
                .addGap(32, 32, 32))
        );

        menuopciones.setText("Opciones");

        creadopor.setText("Creado por");
        creadopor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creadoporActionPerformed(evt);
            }
        });
        menuopciones.add(creadopor);

        jMenuBar1.add(menuopciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void app(){
        String usuario=userfield.getText();
        String clave=String.valueOf(pswdfield.getPassword());
        
        if ((usuario.equals("ventas")) && (clave.compareTo("12345")==0)){
           JOptionPane.showMessageDialog(null,"Bienvenido aL APP");
           app form=new app();
           form.setVisible(true);
           this.dispose();
          
        }
        else {
            JOptionPane.showMessageDialog(null,"Vuelva a intentar");
            pswdfield.setText("");
            userfield.setText(null);
         }
    }    
        
    private void pswdfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswdfieldActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:
    app();    
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void creadoporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creadoporActionPerformed
        // TODO add your handling code here:
    new acerca(this, true).setVisible(true);    
    }//GEN-LAST:event_creadoporActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiapp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem creadopor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel loginfoto;
    private javax.swing.JMenu menuopciones;
    private javax.swing.JPanel panel1;
    private javax.swing.JLabel pswd;
    private javax.swing.JPasswordField pswdfield;
    private javax.swing.JLabel user;
    private javax.swing.JTextField userfield;
    // End of variables declaration//GEN-END:variables
}
